print("-"*100)
length =eval(input("ENTER A LENGTH OF RECTANGLE  :"))
breath=eval(input("ENTER A BREADTH OF RECTANGLE:"))
print("-"*100)
area =length*breath
perimeter =2*(length+breath)
print("AREA OF RECTANGLE IS  :", area,"sq cm")
print("PERIMETER OF RECTANGLR IS :", perimeter,"cm")
print("-"*100)
print(" DAY - 02 COMPLETED :)  ")
print("-"*100)